CREATE DATABASE IF NOT EXISTS sip CHARACTER SET utf8mb4;
USE sip;
CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS students(id INT AUTO_INCREMENT PRIMARY KEY, roll_no VARCHAR(20) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(100), phone VARCHAR(20), class_name VARCHAR(30), dob DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS subjects(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS attendance(id INT AUTO_INCREMENT PRIMARY KEY, student_id INT NOT NULL, att_date DATE NOT NULL, status ENUM('Present','Absent','Late') NOT NULL, UNIQUE(student_id,att_date), FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS grades(id INT AUTO_INCREMENT PRIMARY KEY, student_id INT NOT NULL, subject_id INT NOT NULL, exam VARCHAR(40) NOT NULL, marks DECIMAL(5,2) NOT NULL, max_marks DECIMAL(5,2) NOT NULL DEFAULT 100, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE, FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE);
INSERT IGNORE INTO subjects(name) VALUES ('Mathematics'),('Science'),('English'),('Social Studies'),('Computer Science');
